### ISSUE TITLE
Add vyprnvpn as a provider

### ISSUE THREAD

**Issue by nidayand** [schmas/docker-openvpn-client#4]
I made an attempt but obviously failed terribly :-) If someone can assist and add Vyprvpn as a provider I'd be really happy!

Here are the OpenVPN files https://support.goldenfrog.com/hc/en-us/articles/225607167-Where-can-I-find-the-OpenVPN-files-

Thanks!

**Comment by nathairtras** [comment]
PR in: https://github.com/schmas/docker-openvpn-client/pull/8

**Comment by nidayand** [comment]
Thanks
